# Generated by Django 4.1.4 on 2024-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="profile/", verbose_name="Image"
            ),
        ),
    ]
